parameters:
#    ecl_social.example.class: ECL\SocialBundle\Example

services:
#    ecl_social.example:
#        class: %ecl_social.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
