parameters:
#    ecl_articles.example.class: ECL\ArticlesBundle\Example

services:
#    ecl_articles.example:
#        class: %ecl_articles.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
