<?php
namespace ECL\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{

    public function getById()
    {
        $dql = 'select r.id, r.name from ECLDefaultBundle:Role r';
        $em = $this->getEntityManager();
        $query = $em->createQuery($dql);
        $result = array();
        foreach ($query->getResult() as $item) {
            $result [$item['id']]= $item['name']; 
        }
        
        return $result;
    }
    
}
