<?php
namespace ECL\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function getChildren($user_id = false)
    {
        $dql = 'select u.id, u.username, u.email, u.alias
        from ECLDefaultBundle:User u
        where u.id!=:id';
        $em = $this->getEntityManager();
        $query = $em->createQuery($dql)
                    ->setParameter('id', $user_id);

        return $query->getResult();
    }
    
}
