parameters:
#    ecl_home.example.class: ECL\HomeBundle\Example

services:
#    ecl_home.example:
#        class: %ecl_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
