<?php

namespace ECL\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticlesExtendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesExtendRepository extends EntityRepository
{
}