parameters:
#    ecl_about.example.class: ECL\AboutBundle\Example

services:
#    ecl_about.example:
#        class: %ecl_about.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
